# Generated by Django 4.1.3 on 2022-11-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("description", models.CharField(max_length=100)),
                ("seller_username", models.CharField(max_length=15)),
                ("buyer_username", models.CharField(max_length=15)),
                ("status", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=1, max_digits=4)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=40)),
            ],
        ),
    ]
