# Generated by Django 4.1.3 on 2022-11-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="buyer_username",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("SALE", "Sale"),
                    ("SOLD", "Sold"),
                    ("PURCHASED", "Purchased"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user", name="email", field=models.EmailField(max_length=254),
        ),
    ]
