# Generated by Django 4.1.3 on 2022-11-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appshop", "0002_alter_item_buyer_username_alter_item_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
