# Generated by Django 4.1.3 on 2022-11-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appshop", "0003_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("SALE", "Sale"), ("SOLD", "Sold"), ("WAITING", "Waiting")],
                max_length=10,
            ),
        ),
    ]
