# Generated by Django 4.1.3 on 2022-12-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appshop", "0004_alter_item_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="buyer_username", new_name="buyer",
        ),
        migrations.RenameField(
            model_name="item", old_name="seller_username", new_name="seller",
        ),
    ]
