# Generated by Django 4.1.3 on 2022-12-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appshop", "0005_rename_buyer_username_item_buyer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("WAITING", "Waiting"), ("SALE", "Sale"), ("SOLD", "Sold")],
                max_length=10,
            ),
        ),
    ]
