# Generated by Django 4.1.3 on 2022-12-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appshop", "0006_alter_item_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
