# Generated by Django 4.1.3 on 2022-12-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appshop", "0007_alter_item_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
