# Generated by Django 4.1.3 on 2022-12-20 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appshop", "0008_item_date_modified_alter_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="username_buyer",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="seller",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="username_seller",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
